t1 = str(input('Digite sua primeira tarefa: '))
t2 = str(input('Digite sua segunda tarefa: '))
t3 = str(input('Digite sua terceira tarefa: '))
t4 = str(input('Digite sua quarta tarefa: '))
t5 = str(input('Digite sua quinta tarefa: '))
t6 = str(input('Digite sua sexta tarefa: '))
t7 = str(input('Digite sua setima tarefa: '))
t8 = str(input('Digite sua oitava tarefa: '))
t9 = str(input('Digite sua nona tarefa: '))
t10 = str(input('Digite sua decima tarefa: '))

print("suas tarefas do dia são: ")
print(f'1° = {t1}')
print(f'2° = {t2}')
print(f'3° = {t3}')
print(f'4° = {t4}')
print(f'5° = {t5}')
print(f'6° = {t6}')
print(f'7° = {t7}')
print(f'8° = {t8}')
print(f'9° = {t9}')
print(f'10° = {t10}')
